### ISSUE TITLE
DO_ON_INIT doesn't work w/ gcc or clang

### ISSUE THREAD

**Issue by josharenson** [cppal/hashed_logger#1]
You mentioned during your talk at CppCon that there might be a workaround for this, was hoping you could post here.

**Comment by cppal** [comment]
Hi Josh. Thanks for your interest in my talk, I hope you enjoyed it!

There were two workarounds which audience members presented to me at various times, which I then added to my presentation:

1. The "crazy" one: https://godbolt.org/z/b8bxaMxo7
2. And the non-standard one, which I haven't listed explicitly but should be possible using the "init_array" gcc feature presented in this comment: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=97771#c7

I hope you find this useful.
Andrei

**Comment by josharenson** [comment]
Thanks for the quick response!
